name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          node-version: '16.17.1'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            su - ubuntu
            ${{ secrets.PASSWORD }}
            cd bible25
            cd back-refact
            node -v
            yarn
            # yarn build
            # pm2 reload backend-refact
