name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            # cd bible25
            # cd back-refact
            echo ${{secrets.PASSWORD}} | sudo -S nvm -v

            # echo ${{secrets.PASSWORD}} | sudo -S yarn
            # echo ${{secrets.PASSWORD}} | sudo -S yarn build

            # yarn
            # yarn build
            # pm2 reload backend-refact
